#!/usr/bin/env bash
# Wave-187 FW-1 — structural / coding-standard drift audit.
#
# Companion to scripts/design-drift-audit.sh (design tokens) and
# scripts/check-security-patterns.sh (dangerouslySetInnerHTML). This script
# counts the 8 structural violation classes those two do NOT cover:
#   raw hex colour, inline style={{, raw fetch() outside lib/api/, console.*,
#   `as any`, JSX component >400 LOC, page.tsx >200 LOC, store file >800 LOC.
#
# Output: docs/audit-reports/structural-snapshot.md (overwritten each run,
# checked in so PRs see the delta).
#
# Modes (args passed via `npm run check:structural -- <flag>`):
#   (no flag)          audit + write snapshot, ALWAYS exit 0 (warn mode — FW-1)
#   --update-baseline  write scripts/.structural-baseline.json from current counts
#   --ratchet          exit 1 if any count exceeds its baseline, else exit 0
#
# Warn-mode is the FW-1 default. Hard-block graduation is an explicit FW-3
# decision per docs/specs/wave-187_MASTER_SPEC.md §3.2 — this script never
# blocks on its own.

set -uo pipefail   # NOT -e — git grep exits 1 on no-match, which is expected

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

REPORT="docs/audit-reports/structural-snapshot.md"
BASELINE="$REPO_ROOT/scripts/.structural-baseline.json"
TIMESTAMP="$(date +%Y-%m-%d)"

# git grep respects .gitignore (node_modules, .next, .claude excluded). PCRE
# (-P) gives \b word boundaries + lookbehind, which macOS BRE/ERE lacks.
PATHSPECS=(
  'app/**'
  'components/**'
  'lib/**'
  ':(exclude)**/*.test.*'
  ':(exclude)**/*.spec.*'
)

count_files() { git grep -lP "$1" -- "${PATHSPECS[@]}" 2>/dev/null | wc -l | tr -d ' '; }
count_total() { git grep -cP "$1" -- "${PATHSPECS[@]}" 2>/dev/null | awk -F: '{s+=$2} END {print s+0}'; }

# Count files read from stdin whose line count exceeds threshold $1.
loc_over() {
  local t="$1" n=0 l
  while IFS= read -r f; do
    [ -f "$f" ] || continue
    l=$(wc -l < "$f" 2>/dev/null | tr -d ' ')
    [ "${l:-0}" -gt "$t" ] && n=$((n + 1))
  done
  echo "$n"
}

# --- Design-system / coding-standard violations (file or instance counts) ---
HEX='#([0-9a-fA-F]{6}|[0-9a-fA-F]{3})\b'
raw_hex_files="$(count_files "$HEX")"
# Dashboard-strict: components/site (marketing) has a separate token system
# where some hex is sanctioned (DESIGN_SYSTEM.md §Marketing). Strict count is
# the real must-fix number; total is informational.
raw_hex_strict="$(git grep -lP "$HEX" -- 'app/**' 'components/**' 'lib/**' ':(exclude)components/site/**' ':(exclude)**/*.test.*' ':(exclude)**/*.spec.*' 2>/dev/null | wc -l | tr -d ' ')"
inline_style_files="$(count_files 'style=\{\{')"
# Raw fetch outside lib/api/. Negative lookbehind drops refetch/prefetch.
raw_fetch_files="$(git grep -lP '(?<![A-Za-z])fetch\(' -- 'app/**' 'components/**' 'lib/**' ':(exclude)lib/api/**' ':(exclude)**/*.test.*' ':(exclude)**/*.spec.*' 2>/dev/null | wc -l | tr -d ' ')"
console_instances="$(count_total '\bconsole\.')"
as_any_instances="$(count_total '\bas any\b')"

# --- LOC invariants (per global decompose rule + spec §3.2) ---
comp_over_400="$(git ls-files app components | grep -E '\.tsx$' | grep -vE '/page\.tsx$|\.(test|spec)\.' | loc_over 400)"
page_over_200="$(git ls-files app | grep -E '/page\.tsx$' | loc_over 200)"
store_over_800="$(git ls-files lib/store | grep -E '\.ts$' | loc_over 800)"

cat > "$REPORT" <<EOF
# Structural Drift Snapshot

**Generated**: $TIMESTAMP
**Scope**: app/ + components/ + lib/ (tests excluded; git-grep respects .gitignore)
**Tool**: scripts/check-structural.sh (wave-187 FW-1)

Companion to design-drift-snapshot.md (tokens) and check:security (XSS). Counts
the structural + coding-standard classes those do not cover. Lower is better;
counts fall as FW-2..5 sweeps land.

## Violation counts

| Class | Count | Target / rule |
|---|---|---|
| Raw hex colours (files, all) | $raw_hex_files | dashboard: CSS vars only; marketing: token allowlist |
| Raw hex colours (files, dashboard-strict) | $raw_hex_strict | excludes components/site/ (separate token system) |
| Inline \`style={{\` (files) | $inline_style_files | Tailwind / design-system classes |
| Raw \`fetch()\` outside lib/api/ (files) | $raw_fetch_files | always use apiClient |
| \`console.*\` (instances) | $console_instances | error state / proper logging |
| \`as any\` (instances) | $as_any_instances | explicit types |
| JSX components > 400 LOC | $comp_over_400 | decompose (global rule) |
| \`page.tsx\` > 200 LOC | $page_over_200 | assembly-only |
| Store files > 800 LOC | $store_over_800 | slice by domain |

## Mode

Warn-mode (FW-1). This audit never blocks. Hard-block graduation is an FW-3
decision per docs/specs/wave-187_MASTER_SPEC.md §3.2. Run with \`--ratchet\` in
CI once a baseline is set to prevent regressions.

Generated by \`npm run check:structural\` — re-run after any sweep for the delta.
EOF

echo "✓ Wrote $REPORT"
echo
echo "Structural counts:"
echo "  raw hex files (all/strict):   $raw_hex_files / $raw_hex_strict"
echo "  inline style files:           $inline_style_files"
echo "  raw fetch files (non-api):    $raw_fetch_files"
echo "  console.* instances:          $console_instances"
echo "  as any instances:             $as_any_instances"
echo "  components > 400 LOC:          $comp_over_400"
echo "  page.tsx > 200 LOC:            $page_over_200"
echo "  stores > 800 LOC:             $store_over_800"

# --- Baseline write (--update-baseline) ---
if [ "${1:-}" = "--update-baseline" ]; then
  cat > "$BASELINE" <<JSON
{
  "raw_hex_files": $raw_hex_files,
  "raw_hex_strict": $raw_hex_strict,
  "inline_style_files": $inline_style_files,
  "raw_fetch_files": $raw_fetch_files,
  "console_instances": $console_instances,
  "as_any_instances": $as_any_instances,
  "comp_over_400": $comp_over_400,
  "page_over_200": $page_over_200,
  "store_over_800": $store_over_800,
  "generatedAt": "$TIMESTAMP"
}
JSON
  echo
  echo "✓ Baseline updated at $(basename "$BASELINE")"
  exit 0
fi

# --- Ratchet check (--ratchet) ---
if [ "${1:-}" = "--ratchet" ]; then
  if [ ! -f "$BASELINE" ]; then
    echo
    echo "⚠ No baseline at $BASELINE — run with --update-baseline first."
    exit 0   # never fail CI on first run
  fi
  fail=0
  check_cat() {
    local name="$1" current="$2" baseline
    baseline="$(node -pe "JSON.parse(require('fs').readFileSync('$BASELINE','utf8')).$name" 2>/dev/null || echo 0)"
    if [ "$current" -gt "$baseline" ]; then
      printf "✗ %s: %d (baseline %d, +%d)\n" "$name" "$current" "$baseline" "$((current - baseline))"
      fail=1
    fi
  }
  echo
  echo "Ratchet check against $(basename "$BASELINE"):"
  check_cat raw_hex_files "$raw_hex_files"
  check_cat inline_style_files "$inline_style_files"
  check_cat raw_fetch_files "$raw_fetch_files"
  check_cat console_instances "$console_instances"
  check_cat as_any_instances "$as_any_instances"
  check_cat comp_over_400 "$comp_over_400"
  check_cat page_over_200 "$page_over_200"
  check_cat store_over_800 "$store_over_800"
  if [ "$fail" -eq 1 ]; then
    echo
    echo "Structural ratchet failed. Either sweep the offending class to ≤ baseline,"
    echo "or if the increase is intentional run: npm run check:structural -- --update-baseline"
    exit 1
  fi
  echo "✓ All classes within baseline."
fi

exit 0
