#!/usr/bin/env bash
# Wave-44 — design system drift audit script.
#
# Counts violations of the design-system contract across the codebase.
# Complements the new ESLint rules (no-raw-control-height,
# no-raw-text-px-size) by also surfacing patterns ESLint can't easily
# catch: cross-file primitive drift, spacing inconsistency, missing
# tokens, raw shadow values, hard-coded dark-mode colours.
#
# Output: docs/audit-reports/design-drift-snapshot.md (overwritten each
# run — checked in so PRs can see deltas).
#
# Run:
#   npm run check:design-drift
#
# Designed to be safe to run repeatedly. Exit code is always 0 (audit,
# not gate). Promote to a hard gate in CI after the recommended sweeps
# land.

set -uo pipefail   # NOT -e — grep exit 1 on no-match is expected

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

# Use git grep (always available wherever git is, respects .gitignore,
# fast). Earlier prototype used ripgrep, which is not reliably installed
# in all shells — `rg` in this user's interactive zsh is a shell function
# that delegates to the Claude Code executable and does not resolve under
# bash child processes. git grep is the portable choice.

REPORT="docs/audit-reports/design-drift-snapshot.md"
TIMESTAMP="$(date +%Y-%m-%d)"

# Scoping — what we audit. git grep auto-respects .gitignore (so .claude,
# node_modules, .next, etc. are excluded). We exclude components/site
# explicitly (separate token system) and test/spec files.
PATHSPECS=(
  'app/**'
  'components/**'
  'lib/**'
  ':(exclude)components/site/**'
  ':(exclude)**/*.test.*'
  ':(exclude)**/*.spec.*'
)

count_files() {
  # Number of FILES that contain at least one match.
  # -P enables PCRE which supports \b word boundaries (BRE/ERE on macOS does not).
  git grep -lP "$1" -- "${PATHSPECS[@]}" 2>/dev/null | wc -l | tr -d ' '
}

count_total() {
  # Total match count across all files.
  git grep -cP "$1" -- "${PATHSPECS[@]}" 2>/dev/null | awk -F: '{s+=$2} END {print s+0}'
}

raw_control_heights="$(count_total '\bh-[5-9]\b|\bh-1[0124]\b')"
raw_text_px="$(count_total '\btext-\[(1[2-9]|2[0-9]|3[0-9])px\]')"
raw_paddings="$(count_total '\bp-[5-9]\b|\bp-1[0-4]\b')"
raw_gaps="$(count_total '\bgap-[5-9]\b|\bgap-1[0-4]\b')"
tinted_surface_files="$(count_files '\bbg-(emerald|amber|blue|red|purple|orange|pink|cyan|lime|teal|indigo|violet|fuchsia|rose)-(400|500|600)/[0-9]+\b')"
raw_shadows="$(count_total '\bshadow-\[')"
dark_only_colors="$(count_total '\bbg-(zinc|slate|gray|neutral|stone)-(800|900|950)\b')"

cat > "$REPORT" <<EOF
# Design Drift Snapshot

**Generated**: $TIMESTAMP
**Scope**: app/ + components/ + lib/ (excluding components/site/, tests)
**Tool**: scripts/design-drift-audit.sh

This is an automated snapshot of design-system violations. ESLint catches some of these inline; the snapshot catches cross-file totals + pattern families ESLint can't easily express.

## Violation counts

| Category | Count | Token / pattern to use |
|---|---|---|
| Raw control heights (h-5 through h-16) | $raw_control_heights | h-cta (36px) / h-control (32px) / h-chip (28px) / h-icon (24px) |
| Raw pixel text sizes (text-[12px+]) | $raw_text_px | text-xs / text-sm / text-base / text-lg / text-xl |
| Raw paddings (p-5 through p-14) | $raw_paddings | Tailwind p-* scale or design tokens |
| Raw gaps (gap-5 through gap-14) | $raw_gaps | Tailwind gap-* scale |
| Tinted-surface files (bg-{color}-500/N) | $tinted_surface_files | Toast pattern (surface + colored border) |
| Raw shadows (shadow-[...]) | $raw_shadows | Tailwind shadow-* scale or design tokens |
| Dark-only colours (bg-zinc-900 etc.) | $dark_only_colors | --surface-* CSS vars |

## How to read

- Lower is better. Counts drop as sweeps land.
- ESLint rules with status "error" prevent the count from rising.
- A category with status "warn" allows existing violations but blocks new ones in modified files (lint-staged hook).

## Sweep priorities

Highest impact first (most violations × highest user-visible drift):

1. Raw control heights — every button / input that lands on a different page renders at a different size. Sweep to h-cta / h-control / h-chip / h-icon.
2. Tinted-surface files — accumulated despite the existing no-tinted-surface-bg rule (still at warn). Promote to error after the sweep.
3. Raw text px — affects readability hierarchy across pages.

## Generated by

\`npm run check:design-drift\` — \`scripts/design-drift-audit.sh\`. Re-run after any sweep to see the delta.
EOF

echo "✓ Wrote $REPORT"
echo
echo "Top totals:"
echo "  raw control heights: $raw_control_heights"
echo "  raw text px:         $raw_text_px"
echo "  raw paddings:        $raw_paddings"
echo "  raw gaps:            $raw_gaps"
echo "  tinted surface files: $tinted_surface_files"
echo "  raw shadows:         $raw_shadows"
echo "  dark-only colours:   $dark_only_colors"

# Wave-44b — one-way ratchet against scripts/.design-drift-baseline.json.
# Pass --ratchet to enforce: fail if any count exceeded its baseline.
# Pass --update-baseline to write the current counts as new baseline.
# Wave-42 audit recommended this as the #2 highest-leverage fix.
BASELINE="$REPO_ROOT/scripts/.design-drift-baseline.json"

if [ "${1:-}" = "--update-baseline" ]; then
  cat > "$BASELINE" <<JSON
{
  "raw_control_heights": $raw_control_heights,
  "raw_text_px": $raw_text_px,
  "raw_paddings": $raw_paddings,
  "raw_gaps": $raw_gaps,
  "tinted_surface_files": $tinted_surface_files,
  "raw_shadows": $raw_shadows,
  "dark_only_colors": $dark_only_colors,
  "generatedAt": "$TIMESTAMP"
}
JSON
  echo
  echo "✓ Baseline updated at $(basename "$BASELINE")"
  exit 0
fi

if [ "${1:-}" = "--ratchet" ]; then
  if [ ! -f "$BASELINE" ]; then
    echo
    echo "⚠ No baseline at $BASELINE — run with --update-baseline first."
    exit 0   # don't fail CI on first run
  fi
  fail=0
  check_cat() {
    local name="$1" current="$2"
    local baseline
    baseline="$(node -pe "JSON.parse(require('fs').readFileSync('$BASELINE','utf8')).$name" 2>/dev/null || echo 0)"
    if [ "$current" -gt "$baseline" ]; then
      printf "✗ %s: %d (baseline %d, +%d)\n" "$name" "$current" "$baseline" "$((current - baseline))"
      fail=1
    fi
  }
  echo
  echo "Ratchet check against $(basename "$BASELINE"):"
  check_cat raw_control_heights "$raw_control_heights"
  check_cat raw_text_px "$raw_text_px"
  check_cat raw_paddings "$raw_paddings"
  check_cat raw_gaps "$raw_gaps"
  check_cat tinted_surface_files "$tinted_surface_files"
  check_cat raw_shadows "$raw_shadows"
  check_cat dark_only_colors "$dark_only_colors"
  if [ "$fail" -eq 1 ]; then
    echo
    echo "Design-drift ratchet failed. Either:"
    echo "  (a) Sweep the offending category to bring count to ≤ baseline, OR"
    echo "  (b) If the increase is intentional, run: bash scripts/design-drift-audit.sh --update-baseline"
    exit 1
  fi
  echo "✓ All categories within baseline."
fi
