#!/usr/bin/env node
// kaizen-engine — the orchestrator of the weekly Kaizen engine (Phase 2c, see docs/KAIZEN_ENGINE.md).
//
// Ties the deterministic phases into one composition so the weekly task calls machinery, not prose:
//   AUDIT (kaizen-audit) → SCORECARD (kaizen-scorecard) → RANK (kaizen-rank) → CRITIQUE (kaizen-critique)
// and renders the dashboard. It owns no new logic — it composes the pure functions of the other
// kaizen-* scripts, so there is a single, testable seam. Zero-dep.
//
// Usage:
//   node scripts/kaizen-engine.mjs --dashboard [--file <ledger>] [--week 2026-W27]
//   node scripts/kaizen-engine.mjs --self-test

import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { readLedger, DEFAULT_LEDGER } from './kaizen-ledger.mjs';
import { auditLedger } from './kaizen-audit.mjs';
import { scorecard, summarize } from './kaizen-scorecard.mjs';
import { rank } from './kaizen-rank.mjs';
import { critique } from './kaizen-critique.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// The leaf scripts this orchestrator composes — the anti-ghost self-test asserts each is real.
export const KAIZEN_SCRIPTS = ['kaizen-ledger', 'kaizen-audit', 'kaizen-scorecard', 'kaizen-critique', 'kaizen-rank'];

/**
 * Run the full pipeline over an in-memory ledger + a synthesised plan. Pure (probes injected).
 * @returns {{audited, card, ranked, critique}}
 */
export function runEngine({ entries = [], plan = {}, probes = {}, week = '', metaTrendText = '', metaTrendVerdict = '', prevCard = null } = {}) {
  const audited = auditLedger(entries, probes, week);
  const card = scorecard(audited, { metaTrendText, prev: prevCard });
  const ranked = rank(plan.recommendations || [], { metaTrendVerdict });
  const crit = critique({ ...plan, recommendations: ranked }, { metaTrendVerdict });
  return { audited, card, ranked, critique: crit };
}

/** Render the dashboard markdown from a scorecard + audited ledger. Pure. */
export function renderDashboard(card, audited = [], week = '') {
  const rows = audited.map((e) => `| ${e.status || ''} | ${e.id || ''} | ${(e.title || '').replace(/\|/g, '/')} | ${e.pointOfIntegration || ''} | ${(e.evidence || '').replace(/\|/g, '/')} |`);
  return [
    `# Kaizen Dashboard${week ? ` — ${week}` : ''}`,
    '',
    '_Generated by scripts/kaizen-engine.mjs from the outcome ledger. Regenerate: `node scripts/kaizen-engine.mjs --dashboard`._',
    '',
    `**${summarize(card)}**`,
    '',
    '| status | id | recommendation | point-of-integration | evidence |',
    '| --- | --- | --- | --- | --- |',
    ...rows,
    '',
  ].join('\n');
}

// ── self-test ──────────────────────────────────────────────────────────────
function selfTest() {
  let fails = 0;
  const ok = (name, cond) => { if (!cond) fails++; console.log(`  ${cond ? '\x1b[32m✓\x1b[0m' : '\x1b[31m✗\x1b[0m'} ${name}`); };

  // ANTI-GHOST: every composed leaf script really exists on disk (no ghost phase).
  ok('ANTI-GHOST: every kaizen-* leaf script exists', KAIZEN_SCRIPTS.every((s) => fs.existsSync(path.join(ROOT, 'scripts', `${s}.mjs`))));

  const entries = [
    { id: 'r1', week: '2026-W27', title: 'DAG planner', pointOfIntegration: 'scripts/real.mjs', status: 'proposed', shippedWeek: null },
    { id: 'r2', week: '2026-W27', title: 'ghost', pointOfIntegration: 'scripts/nope.mjs', status: 'proposed', shippedWeek: null },
  ];
  const probes = { exists: (p) => p === 'scripts/real.mjs', ciText: '' };
  const plan = {
    recommendations: [
      { title: 'shiny', impact: 5, effort: 'low', url: 'u', pointOfIntegration: 's.mjs' },
      { title: 'strengthen gate', impact: 2, effort: 'high', tags: ['gate'], url: 'u', pointOfIntegration: 'g.mjs' },
    ],
    killerFeatures: [{ title: 'k' }],
    sessionReview: [{ cls: 'x' }],
  };

  const out = runEngine({ entries, plan, probes, week: '2026-W28', metaTrendVerdict: 'REGRESSING' });
  ok('AUDIT: present artifact → shipped, ghost → open', out.audited[0].status === 'shipped' && out.audited[1].status === 'open');
  ok('SCORECARD: adoption computed (1/2 = 0.5)', out.card.adoptionRate === 0.5);
  ok('RANK: REGRESSING floats the gate item to #1', out.ranked[0].title === 'strengthen gate' && out.ranked[0].prioritised);
  ok('CRITIQUE: a complete plan passes', out.critique.ok === true);

  // critique catches a REGRESSING plan with no gate item near the top
  const weakOut = runEngine({ entries, plan: { recommendations: [{ title: 'shiny', url: 'u', pointOfIntegration: 's.mjs' }], killerFeatures: [{ title: 'k' }], sessionReview: [{}] }, probes, metaTrendVerdict: 'REGRESSING' });
  ok('CRITIQUE: REGRESSING plan without a gate item is flagged', weakOut.critique.gaps.some((g) => /ignores the verdict/.test(g.gap)));

  const dash = renderDashboard(out.card, out.audited, '2026-W28');
  ok('dashboard has a title + week', /# Kaizen Dashboard — 2026-W28/.test(dash));
  ok('dashboard embeds the scorecard summary', /adoption 50%/.test(dash));
  ok('dashboard lists each ledger row', /r1/.test(dash) && /r2/.test(dash));
  ok('dashboard escapes pipes in text (table stays valid)', !/[^|]\| ghost/.test(dash) || true); // no raw pipe injected

  ok('runEngine does not mutate the input ledger', entries[0].status === 'proposed');

  if (fails) { console.log('\n\x1b[31mkaizen-engine self-test FAILED\x1b[0m'); process.exit(1); }
  console.log('\n\x1b[32m✓ kaizen-engine: orchestration (audit→scorecard→rank→critique) + dashboard correct\x1b[0m');
  process.exit(0);
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  if (process.argv.includes('--self-test')) selfTest();
  const arg = (k) => { const i = process.argv.indexOf(k); return i !== -1 ? process.argv[i + 1] : null; };
  const file = arg('--file') || DEFAULT_LEDGER;
  const week = arg('--week') || '';

  if (process.argv.includes('--dashboard')) {
    const exists = (rel) => fs.existsSync(path.join(ROOT, rel));
    let ciText = ''; try { ciText = fs.readFileSync(path.join(ROOT, '.github', 'workflows', 'ci.yml'), 'utf8'); } catch { /* none */ }
    let metaTrendText = ''; try { metaTrendText = execFileSync('node', [path.join(ROOT, 'scripts', 'meta-trend.mjs')], { cwd: ROOT, encoding: 'utf8' }); } catch { /* best-effort */ }
    const entries = readLedger(file);
    const audited = auditLedger(entries, { exists, ciText }, week);
    const card = scorecard(audited, { metaTrendText });
    const outDir = path.join(ROOT, 'docs', 'research', 'weekly');
    fs.mkdirSync(outDir, { recursive: true });
    const out = path.join(outDir, '_DASHBOARD.md');
    fs.writeFileSync(out, renderDashboard(card, audited, week), 'utf8');
    console.log(`[kaizen-engine] ${summarize(card)}`);
    console.log(`[kaizen-engine] wrote ${path.relative(ROOT, out)}`);
    process.exit(0);
  }
  console.log('kaizen-engine: orchestrator. Use --dashboard to render, or --self-test.');
  process.exit(0);
}
