#!/usr/bin/env bash
# Wave-34 — skills aging audit.
#
# Process Engineer's manual job: walk through .claude/skills/, count
# citations in retros / commits / specs, mark stale ones for
# deprecation review. Most agent systems leave this to drift; we
# automate it.
#
# Output: a markdown report at .claude/audit-reports/skills-aging.md
# listing each skill with its citation count and a verdict:
#   - fresh    : ≥ 3 citations in last 5 waves  (healthy)
#   - active   : 1-2 citations in last 5 waves  (in use)
#   - aging    : 0 citations in last 5 waves    (review candidate)
#   - dormant  : 0 citations in last 10 waves   (deprecate candidate)
#
# Usage:
#   npm run skills:audit          → writes the report
#   bash scripts/skills-audit.sh  → same, direct invocation
#
# Re-run periodically (suggested: at the start of each major wave).
# Dormant skills should be reviewed with the user before deletion —
# a dormant skill is sometimes "evergreen advice still applicable, just
# not specifically cited" (e.g. surface-audit-before-touch may apply
# in every wave without explicit mention).

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

SKILLS_DIR=".claude/skills"
RETROS_DIR="docs/retros"
SPECS_DIR="docs/specs"
REPORT=".claude/audit-reports/skills-aging.md"

mkdir -p "$(dirname "$REPORT")"

# Find the N latest waves by retro filename. We use retros as the
# authoritative source of "what waves happened" — every shipped wave
# should have one (enforced by the wave-30 commit-msg hook).
LATEST_5_WAVES=$(ls -1 "$RETROS_DIR"/wave-*.md 2>/dev/null \
  | xargs -n1 basename 2>/dev/null \
  | sed 's/wave-//; s/\.md$//' \
  | sort -V \
  | tail -5 \
  | tr '\n' ' ' || echo "")

LATEST_10_WAVES=$(ls -1 "$RETROS_DIR"/wave-*.md 2>/dev/null \
  | xargs -n1 basename 2>/dev/null \
  | sed 's/wave-//; s/\.md$//' \
  | sort -V \
  | tail -10 \
  | tr '\n' ' ' || echo "")

count_citations() {
  local skill_slug="$1"
  local waves="$2"
  local count=0
  for w in $waves; do
    # Match in retros (full text)
    if [ -f "$RETROS_DIR/wave-${w}.md" ]; then
      if grep -q "$skill_slug" "$RETROS_DIR/wave-${w}.md" 2>/dev/null; then
        count=$((count + 1))
      fi
    fi
    # Match in specs (full text)
    if [ -f "$SPECS_DIR/wave-${w}_MASTER_SPEC.md" ]; then
      if grep -q "$skill_slug" "$SPECS_DIR/wave-${w}_MASTER_SPEC.md" 2>/dev/null; then
        count=$((count + 1))
      fi
    fi
  done
  echo "$count"
}

# Build the report
{
  echo "# Skills aging audit"
  echo ""
  echo "**Date**: $(date +%Y-%m-%d)"
  echo "**Generated by**: scripts/skills-audit.sh (wave-34)"
  echo ""
  echo "Last 5 waves analysed: \`$LATEST_5_WAVES\`"
  echo "Last 10 waves analysed (for dormant detection): \`$LATEST_10_WAVES\`"
  echo ""
  echo "| Skill | Citations (last 5) | Citations (last 10) | Status |"
  echo "|-------|----------|----------|--------|"

  for skill in "$SKILLS_DIR"/*.md; do
    base=$(basename "$skill" .md)
    [ "$base" = "_INDEX" ] && continue
    [ "$base" = "_TEMPLATE" ] && continue
    [ "$base" = "README" ] && continue

    c5=$(count_citations "$base" "$LATEST_5_WAVES")
    c10=$(count_citations "$base" "$LATEST_10_WAVES")

    if [ "$c5" -ge 3 ]; then
      status="🟢 fresh"
    elif [ "$c5" -ge 1 ]; then
      status="🔵 active"
    elif [ "$c10" -ge 1 ]; then
      status="🟡 aging"
    else
      status="🔴 dormant"
    fi

    echo "| \`$base\` | $c5 | $c10 | $status |"
  done

  echo ""
  echo "## Verdict legend"
  echo ""
  echo "- 🟢 **fresh** (≥ 3 in last 5 waves): healthy, keep"
  echo "- 🔵 **active** (1-2 in last 5): in use, keep"
  echo "- 🟡 **aging** (0 in last 5, ≥ 1 in last 10): review candidate — may be evergreen advice that just isn't cited, or a skill that's lost relevance"
  echo "- 🔴 **dormant** (0 in last 10 waves): deprecate candidate — flag for user before deletion"
  echo ""
  echo "## What to do next"
  echo ""
  echo "1. Skim 🟡 aging skills: do they still describe the way we build? Update or deprecate."
  echo "2. For 🔴 dormant skills: open a discussion with the user before deletion. Sometimes a skill IS the right pattern but the recent waves happened not to use it."
  echo "3. For 🟢 fresh skills cited > 4 in last 5 waves: consider promoting from experimental → stable in \`_INDEX.md\`."
} > "$REPORT"

echo "✓ Skills aging audit written to $REPORT"
echo ""
echo "Quick summary:"
grep -c "🔴 dormant" "$REPORT" 2>/dev/null | awk '{print "  🔴 dormant: " $1}'
grep -c "🟡 aging"   "$REPORT" 2>/dev/null | awk '{print "  🟡 aging:   " $1}'
grep -c "🔵 active"  "$REPORT" 2>/dev/null | awk '{print "  🔵 active:  " $1}'
grep -c "🟢 fresh"   "$REPORT" 2>/dev/null | awk '{print "  🟢 fresh:   " $1}'
